apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flask-server
  labels:
    name: flask-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flask-server
  template:
    metadata:
      name: flask-server
      labels:
        name: flask-server
    spec:
      containers:
        - name: flask-server
          image: gcr.io/k8-prod-1089/flask-app:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi